<?php

namespace AppBundle\Repository;

/**
 * AbonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllJoined()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a FROM AppBundle:Abonne a JOIN a.compte c'
            )->getResult();
    }
}
