<?php

namespace AppBundle\Repository;

/**
 * EventorganisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventorganisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
