<?php

namespace AppBundle\Repository;

/**
 * EventsponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsponsorRepository extends \Doctrine\ORM\EntityRepository
{
}
