<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDistinctLieu()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT e.lieu FROM AppBundle:Event e'
            )
            ->getResult();
    }
}
