<?php

namespace AppBundle\Repository;

/**
 * EventFermeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventFermeRepository extends \Doctrine\ORM\EntityRepository
{
}
