<?php

namespace AppBundle\Repository;

/**
 * EventCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
