<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Abonne;

/**
 * ReservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAbonne(Abonne $abonne)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Event e
                    WHERE e IN
                        (SELECT IDENTITY(r.eventFerme) FROM AppBundle:Reservation r WHERE r.abonne = :abonne)'
            )
            ->setParameter("abonne", $abonne)
            ->getResult();
    }
}
